@startuml
!include style.puml
skinparam ArrowFontStyle plain

box External #white
actor User as user
end box

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as logic LOGIC_COLOR
participant ":AddressBookParser" as abp LOGIC_COLOR
participant "ExportCommand" as ec LOGIC_COLOR
participant ":ClipboardProvider" as clipboard LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as model MODEL_COLOR
end box

box Storage STORAGE_COLOR_T1
participant ":FileSystemProvider" as fsp STORAGE_COLOR
participant ":JsonAddressBookUtil" as jabu STORAGE_COLOR
end box

user -> logic : execute("export")
activate logic
logic -> abp : parseCommand("export")
activate abp
abp -> ec : create ExportCommand()
activate ec
abp --> logic : ExportCommand
deactivate abp
logic -> ec : execute(model)
activate ec
ec -> model : getAddressBookFilePath()
activate model
model --> ec : filePath
deactivate model
ec -> fsp : readFile(filePath)
activate fsp
fsp --> ec : fileContent
deactivate fsp
ec -> jabu : readAddressBookFromJsonString(fileContent)
activate jabu
jabu --> ec : AddressBook
deactivate jabu
ec -> clipboard : setString(fileContent)
activate clipboard
clipboard --> ec : void
deactivate clipboard
ec --> logic : CommandResult
deactivate ec
logic --> user : "Copied address book data to clipboard."
deactivate logic
@enduml
