@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Logic as LogicPackage {

package "Parser Classes" as ParserClasses{
}
Class XYZCommand
Class CommandResult
Class "{abstract}\nCommand" as Command

Class SetStatusCommand LOGIC_COLOR_T2
Class TemplateCommand LOGIC_COLOR_T2
Class ImportCommand LOGIC_COLOR_T2
Class ExportCommand LOGIC_COLOR_T2

Class "<<interface>>\nLogic" as Logic
Class LogicManager
}

package Model {
Class HiddenModel #FFFFFF
}

package Storage {
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Logic

LogicManager .right.|> Logic
LogicManager -right->"1" ParserClasses
ParserClasses ..> XYZCommand : <<create>>
ParserClasses ..> SetStatusCommand : <<create>>
ParserClasses ..> TemplateCommand : <<create>>
ParserClasses ..> ImportCommand : <<create>>
ParserClasses ..> ExportCommand : <<create>>

XYZCommand -up-|> Command
SetStatusCommand -up-|> Command
TemplateCommand -up-|> Command
ImportCommand -up-|> Command
ExportCommand -up-|> Command
LogicManager .left.> Command : <<call>>

LogicManager --> Model
LogicManager --> Storage
Storage --[hidden] Model
Command .[hidden]up.> Storage
Command .right.> Model
note right of XYZCommand: XYZCommand = AddCommand, \nFindCommand, etc found originally in AB3

Logic ..> CommandResult
LogicManager .down.> CommandResult
Command .up.> CommandResult : <<create>>
@enduml
